version: '3.3'
services:
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ../backend/.env
    ports:
      - "8080:8080"
    links:
      - database
    networks: 
      - backend
      - database
      - oauth
    depends_on:
      - database
  
  database:
    image: postgres:14.0
    container_name: database
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks: 
      - database

  oauth:
    image: jboss/keycloak:15.0.2
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=password
      - POSTGRES_DB=keycloak 
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=password
    ports:
      - "9090:8080"
    links:
      - database
    networks: 
      - oauth
      - database
    depends_on:
      - database
  
networks:
  backend:
  database:
  oauth:
